export interface ForecastCard {
  [date: string]: {
    temp_high: number;
    temp_low: number;
    weather: string;
  };
}

export interface WeatherCard {
  name: string;
  weather_id: number;
  weather_condition: string;
  weather_main: string;
  weather_icon: string;
  date: string;
  temp: number;
  feels_like: number;
  timezone: number;
}

export interface ForecastObj {
  date: string;
  temp: number;
  weather: {
    id: number;
    main: string;
    description: string;
    icon: string;
  };
}

export interface Coordinates {
  lat: number;
  lon: number;
}
// Generated by https://quicktype.io

export interface JSONMap {
  [code: string]: {
    label: string;
    icon: string;
    image?: string;
  };
}
